Add integration_tests to CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -20,10 +20,27 @@ jobs:
         run: |
           bazelisk test //...
 
+  integration_tests:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout the repository
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
+      - name: Configure bazelrc
+        uses: ./
+        with:
+          remote_header: "foo-bar"
+      - name: Confirm bazelrc was updated
+        shell: bash
+        run: |
+          [[ -e .bazelrc ]] || (echo >&2 ".bazelrc was not found." && exit 1)
+          grep -q -e "--remote_header=foo-bar" .bazelrc || \
+            (echo >&2 "did not find expected setting" && exit 1)
+
   all_ci_tests:
     runs-on: ubuntu-latest
     needs:
       - unit_tests
+      - integration_tests
     if: ${{ always() }}
     steps:
       - uses: cgrindel/gha_join_jobs@794a2d117251f22607f1aab937d3fd3eaaf9a2f5 # v1.2.0
